Add rust environment
AntonKozlov/os226-2022 pull request #1
Opened 2022-09-06 14:29 UTC by AzimMuradov

- update .gitignore
- add additional test script for testing and job for test.yml
- add cargo files and add main.rs

2022-09-06 14:38 UTC, AntonKozlov requested changes

2022-09-06 14:38 UTC, AntonKozlov commented on test/run-rust.sh
> +	( cd $B/.. ; ./target/debug/os226-2022 )
Лучше сделайте просто изменение в run.sh, чтобы было видно что поменялось в этом файле

2022-09-06 14:41 UTC, AzimMuradov commented on test/run-rust.sh
> +	( cd $B/.. ; ./target/debug/os226-2022 )
То есть оставить один shell скрипт и для rust и для c? Просто в таком случае как должен выглядеть вывод и return code запуска теста?

2022-09-06 14:48 UTC, AntonKozlov commented on test/run-rust.sh
> +	( cd $B/.. ; ./target/debug/os226-2022 )
Сделайте просто чтобы проходила ваша версия. Вывод и ret code должны совпадать же, с точки зрения пользователя, всё равно на каком языке написано ПО.

К Github Actions то же самое, сделайте минимально необходимые вам изменения

2022-09-07 09:48 UTC, AntonKozlov requested changes

2022-09-07 09:48 UTC, AntonKozlov commented on .github/workflows/test.yml
> +      - run: cargo build
Давайте просто поменяем make -> cargo, и только.

Я наверно не буду мержить вашу раст версию всё равно. Т.е. ваша ОС будет форком моей, переписанной на расте. Чтобы мне было проще ревьюить и понимать, чем меньше изменений, тем лучше. Мне совершенно не нужно чтобы С версия продолжала у вас работать.

2022-09-07 09:48 UTC, AntonKozlov commented on test/run-rust.sh
> +	( cd $B/.. ; ./target/debug/os226-2022 )
В принципе ОК, но можно было бы проще поменять runmain() в run.sh (без переименования).

Запуск C  версии можно было бы сделать runmain_c() функцией, или как-то так -- для вас, чтобы посмотреть как ведёт себя С версия. Я не буду всё равно смотреть что происходит у вас в Си версии :)

2022-09-07 10:06 UTC, AzimMuradov commented on .github/workflows/test.yml
> +      - run: cargo build
Тогда давайте я уберу весь си код и соответственно поправлю скрипты, CI. При я буду делать PR в ветку `master-rust` или буду делать pr в свой fork :)

2022-09-07 10:30 UTC, AntonKozlov commented on .github/workflows/test.yml
> +      - run: cargo build
Пожалейте меня, чем меньше изменений, тем мне проще. Основывайтесь на #2. Здесь остаётся только поменять main.rs

2022-09-07 15:47 UTC, closed without merging

2022-09-11 10:07 UTC, AntonKozlov commented
см #3