Implement 6th homework
AntonKozlov/os226-2022 pull request #108
Opened 2022-10-29 20:16 UTC by AzimMuradov

К сожалению, я нашел 2 ошибки в проверяющей системе:

1. была проблема командой `timeout` в `run.sh`
2. был недостаточно большой `cnt % 1000` в `2.in`

Подробнее в соответствующих коммитах.

2022-10-30 09:15 UTC, AntonKozlov requested changes

2022-10-30 09:15 UTC, AntonKozlov commented on test/run.sh
> +MAIN=$B/../main
Согласен, спасибо

2022-10-30 09:15 UTC, AntonKozlov commented on test/run.sh
> +	< $1.in timeout 10s $MAIN | diffout $1
Опциональный суффикс, можно взять, для простоты не буду

2022-10-30 09:15 UTC, AntonKozlov commented on test/preempt/2.in
> +app	2	1010	0
Должно работать и без этого, точно не согласен. Ваш текущий код крешится если процесс завершается, соответственно это баг. Поправил тест чтобы это было виднее. https://github.com/AntonKozlov/os226-2022/blob/cf4e9b7c5692764289ef8eecf5468fe26269189c/test/preempt/run-test.sh#L2

```
anton@mercury:~/stuff/os226-2022$ git log -2
commit 56c5d636202ffb0e58352dbb1b1692f385b79f00 (HEAD)
Author: Azim Muradov <azim.muradov.dev@gmail.com>
Date:   Sat Oct 29 23:13:18 2022 +0300

    Implement 6th homework

commit 90edca0fa1b23dc22d26ed9b39d57770025c3571 (origin/master)
Author: Anton Kozlov <akozlov@azul.com>
Date:   Wed Oct 20 20:51:31 2021 +0300

    HW6
anton@mercury:~/stuff/os226-2022$ make
cc -g -MMD -MT sched.o -MF sched.o.d   -c -o sched.o sched.c
cc  apps.o ctx.o ctx_switch.o kernel.o pool.o sched.o syscall.o timer.o tramp.o   -o main
anton@mercury:~/stuff/os226-2022$ ./main < test/preempt/2.in ; echo $?
           sleep id 1 cnt 1005 time 0 reftime 0
           sleep id 1 cnt 1005 time 1000 reftime 1000
           sleep id 1 cnt 1005 time 2000 reftime 2000
           sleep id 1 cnt 1005 time 3000 reftime 3000
           sleep id 1 cnt 1005 time 4000 reftime 4000
Segmentation fault (core dumped)
139
```

2022-10-30 09:22 UTC, AzimMuradov commented on test/run.sh
> +	< $1.in timeout 10s $MAIN | diffout $1
Согласен, суффикс изначально не относился к фиксам, но я в итоге почему-то все равно его оставил :)

2022-10-30 09:41 UTC, AzimMuradov commented on test/preempt/2.in
> +app	2	1010	0
Поправил баг, но на мой взгляд это 2 независимые проблемы.
Проблема с маленьким `cnt % 1000` приводит к тому, что `2.in` отрабатывает раньше, чем `timeout`, что приводит к возврату не того кода (возвращается 0, а должен 124).

Из `run.sh`:

![image](https://user-images.githubusercontent.com/31899809/198872115-ac1df516-79b4-4b38-924c-77be8b1ef5ae.png)

Из https://www.gnu.org/software/coreutils/manual/html_node/timeout-invocation.html:

![image](https://user-images.githubusercontent.com/31899809/198872137-cda523ef-3384-4685-af27-48d15a44a738.png)

2022-10-30 09:54 UTC, AzimMuradov commented on test/preempt/2.in
> +app	2	1010	0
В целом, изменения в cf4e9b7c5692764289ef8eecf5468fe26269189c тоже решают проблему + заметно, если была ошибка (как например у меня в `tasktramp`).

2022-10-31 06:53 UTC, AntonKozlov commented on test/preempt/2.in
> +app	2	1010	0
Ааа, понял. Да, так согласен -- правильный код возврата возврата это 0. `checkfn 2` действительно начинает проверять на 0, я это не указал, спасибо.

2022-10-31 06:59 UTC, closed without merging