retcode and echo v1.
AntonKozlov/os226-2022 pull request #6
Opened 2022-09-09 11:51 UTC by st084331

Читаем построчно
Строку разбиваем на команды разделенные символом ";" 
Команду разбиваем на лексемы по пробелам
retcode храним глобально

2022-09-11 09:47 UTC, AntonKozlov requested changes

2022-09-11 09:47 UTC, AntonKozlov commented on main.c
> +            retcodeInt = -1;
Вашу программу запускают как `main < file`, вы рассчитываете на `main file`

2022-09-11 10:34 UTC, st084331 commented
Исправил, нужно ли для этого делать новый PR?

2022-09-12 19:37 UTC, st084331 commented on main.c
> +            retcodeInt = -1;
Исправил (второй commit)

2022-09-15 16:53 UTC, AntonKozlov commented
> Исправил, нужно ли для этого делать новый PR?

Не, наоборот надо исправлять в открытый, иначе я утону в PR

2022-09-17 09:16 UTC, st084331 commented
Скажите, пожалуйста, это автоматическая проверка? Или этот тест значит, что мое решение неверное? Просто странно, что тест крашится на тесте из batch. Это было бы возможно если бы тестился второй commit, но как я вижу тестится третий, в котором код в main - это Ваш вариант HW1.
<img width="1440" alt="Снимок экрана 2022-09-17 в 12 05 29" src="https://user-images.githubusercontent.com/71183199/190849348-0798fb91-c4ac-46f4-a833-26e1485d7848.png">
<img width="1440" alt="Снимок экрана 2022-09-17 в 12 11 54" src="https://user-images.githubusercontent.com/71183199/190849507-eb7fae42-56dd-4eb9-8d74-7c1c58829d7d.png">
<img width="1440" alt="Снимок экрана 2022-09-17 в 12 12 10" src="https://user-images.githubusercontent.com/71183199/190849509-7ef2107b-8faf-4ce3-98ae-4b4f216cb658.png">

2022-09-19 14:45 UTC, closed without merging